version: '3'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
        container_name: mssql
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'MSSQL_passsword' # 强密码
        ports:
            - 1433:1433
