version: '3.5'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '0601'
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: 'qgaye'
      MYSQL_PASSWORD: '0601'
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/conf:/etc/mysql/conf.d
      - ./data/log:/var/log/mysql
    networks:
      - mysql_net

networks:
  mysql_net:
    name: mysql_net